### ISSUE TITLE
Numaflow UI Redesign

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1032]
# Readonly Operations

```[tasklist]
### Tasks
- [ ] #955
- [x] react router setup
- [x] breadcrumbs and layout setup
- [x] generic summary component for cluster/namespace summary
- [x] summary component for pipeline summary
- [x] namespace summary card
- [x] each pipeline summary card
- [x] pipeline summary
- [x] side panel component
- [x] vertex side panel component
- [x] buffer side panel component
- [x] yaml editor exploration
- [x] yaml editor implementation
- [x] k8s events in namespace summary page
- [ ] k8s events in pipeline summary page
- [ ] k8s events in vertex
- [ ] controller events in namespace summary page
```

# Mutating Operations (Create, Update, Delete)

```[tasklist]
### Tasks
- [x] Create a pipeline
- [x] generic fetcher for creation
- [x] generic fetcher for update
- [x] gederic fetcher for delete
- [x] generic component for editing spec and submitting
- [x] create pipeline component
- [x] create ISB service component
- [x] edit/update pipeline spec in namespace summary page
- [ ] play/pause pipeline in namespace summary page
- [x] edit/update pipeline spec in pipeline summary page
- [x] edit/update vertex spec
- [ ] play/pause pipeline in pipeline summary page
- [x] delete spec
```
```[tasklist]
### Tasks
- [ ] ISB View (pods, logs, etc.)
```
