### ISSUE TITLE
Numaflow on Data-on-EKS

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1411]
https://github.com/awslabs/data-on-eks/issues/382
```[tasklist]
### Tasks
- [ ] https://github.com/numaproj/numaflow/issues/1092
- [ ] https://github.com/numaproj/numaflow/issues/1486
- [ ] Documentation
- [ ] Example with an end-to-end use case
```
