### ISSUE TITLE
Java Reducer SDK update

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#1453]
# Summary

With session window reducer introduced, we updated our proto for reducer. We need to make corresponding changes to java SDK.

```[tasklist]
### Tasks
- [x] Update existing reduce java sdk to make it compatible with the new proto.
- [x] Implement stream reduce java sdk.
- [x] Implement session reduce java sdk.
- [x] E2E Testing
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
