### ISSUE TITLE
use a single server-info for all mapper types

### ISSUE THREAD

**Issue by kohlisid** [numaproj/numaflow#1810]
Improvement: Shall we use one `server-info` for all the mappers, and start the mode based what is written in the file?

_Originally posted by @whynowy in https://github.com/numaproj/numaflow/pull/1778#discussion_r1671666859_
            
```[tasklist]
### Tasks
- [ ] https://github.com/numaproj/numaflow/issues/1836
- [ ] https://github.com/numaproj/numaflow/issues/1838
- [ ] https://github.com/numaproj/numaflow/issues/1837
- [ ] https://github.com/numaproj/numaflow/issues/1846
- [ ] https://github.com/numaproj/numaflow/issues/1849
- [x] Testing single-server info for map
```

**Comment by kohlisid** [comment]
Closing as all tasks completed.
