### ISSUE TITLE
implement source-sink that bypasses ISB

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1901]
```[tasklist]
### Tasks
- [ ] https://github.com/numaproj/numaflow/pull/1904
- [ ] https://github.com/numaproj/numaflow/issues/1908
- [x] emit basic metrics
- [x] lag reader and pending
- [x] integrate with soucer-sinker numaflow-model
- [x] unit testing
```
