### ISSUE TITLE
version compatibility check for Rust numa container

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#1908]
Implement https://github.com/numaproj/numaflow/blob/main/pkg/sdkclient/serverinfo/serverinfo.go#L53
```[tasklist]
### Tasks
- [x] Add server-info support to mono vertex
- [x] Add version compatibility checks to mono vertex
- [ ] https://github.com/numaproj/numaflow/issues/1915
```
