### ISSUE TITLE
Speed up and fix flakiness for e2e tests

### ISSUE THREAD

**Issue by KeranYang** [numaproj/numaflow#1963]
```[tasklist]
### Tasks
- [ ] https://github.com/numaproj/numaflow/issues/1727
- [ ] https://github.com/numaproj/numaflow/issues/1620
- [ ] https://github.com/numaproj/numaflow/issues/1582
- [ ] https://github.com/numaproj/numaflow/issues/1550
- [ ] https://github.com/numaproj/numaflow/issues/1180
- [ ] https://github.com/numaproj/numaflow/issues/1964
- [ ] numaflow installation timeout: https://github.com/numaproj/numaflow/actions/runs/10460461436/job/28966678260 jetstream-e2e
- [ ] https://github.com/numaproj/numaflow/pull/1961
- [ ] https://github.com/numaproj/numaflow/issues/1996
- [x] timeout waiting for isb service ready: https://github.com/KeranYang/numaflow/actions/runs/10549896856/job/29230855579
```

**Comment by KeranYang** [comment]
I am closing this issue because the goal is to solve the e2e flakiness and we haven't seen it for 2 months.
