### ISSUE TITLE
move to bi-directional streaming for source, map, transformer, and sink for better performance

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#2035]
# Summary

The integration between numa and SDK server should be via gRPC Streaming and not unary for better performance. We should even move half-duplex to bi-di.

# Use Cases

Getting Numaflow ready for future performance improvements.

```[tasklist]
### Tasks
- [ ] https://github.com/numaproj/numaflow/issues/2045
- [ ] https://github.com/numaproj/numaflow/issues/2196
- [ ] https://github.com/numaproj/numaflow/issues/2046
- [ ] https://github.com/numaproj/numaflow/issues/2092
- [ ] https://github.com/numaproj/numaflow/issues/2091
- [ ] https://github.com/numaproj/numaflow/pull/2194
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
