### ISSUE TITLE
Implement Tickgen for MonoVertex

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#2113]
# Summary

Pave a path for including builtins into MonoVertex

# Use Cases

support Builtins

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

```[tasklist]
### Tasks
- [ ] https://github.com/numaproj/numaflow/pull/2114
- [ ] https://github.com/numaproj/numaflow/issues/2125
- [ ] https://github.com/numaproj/numaflow/issues/2158
- [ ] https://github.com/numaproj/numaflow/pull/2136
```
