### ISSUE TITLE
Builtin Log Sink for MonoVertex

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#2137]
# Summary

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

```[tasklist]
### Tasks
- [ ] https://github.com/numaproj/numaflow/pull/2141
- [x] Rewrite User-Defined Sink using Sink Trait
- [x] use actor pattern for forwarder
- [ ] Implement Log Sink
- [ ] Integrate the Forwarder with log sink using Numaflow Model
- [ ] LagReader need not be cloneable
- [ ] test coverage
```
