### ISSUE TITLE
Serving as a builtin souce

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#2244]
```[tasklist]
### Tasks
- [x] Move serve-sink code under numaflow-extns
- [ ] https://github.com/numaproj/numaflow/issues/2319
- [x] Pipeline changes to support serving as a builitn source
- [ ] https://github.com/numaproj/numaflow/issues/2350
- [ ] https://github.com/numaproj/numaflow/issues/2364
- [ ] https://github.com/numaproj/numaflow/issues/2281
- [ ] https://github.com/numaproj/numaflow/issues/2280
- [ ] https://github.com/numaproj/numaflow/issues/2308
- [ ] https://github.com/numaproj/numaflow/issues/2318
- [x] Expose response serve functionlity in SDKs for send the response back the serving source
- [x] FMEA Tests
```
