### ISSUE TITLE
JOIN Vertex to join data from more than one Vertices

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#719]
Numaflow should have the ability to JOIN during the following scenarios. 

## JOIN by Key by Window

JOIN by Reduce and using Watermark to close the book. The output will be Keys with Value as an iterator. Please note that the JOIN could be from more than Reduce vertices or consists of one or more Map and Reduce vertices.

![image1](https://user-images.githubusercontent.com/191430/235400110-086723ed-4a7a-4045-8499-5cf0a9582de9.png)

## JOIN on Map/Sink

A pure non-join write to Sink or Map without really joining by any key.

![image2](https://user-images.githubusercontent.com/191430/235400111-d1052241-776e-4f3b-bd7f-7a50ba964387.png)

## Multiple Sources

This could be based on the previous two use-cases.

![image4](https://user-images.githubusercontent.com/191430/235400113-db599930-e926-469c-a051-e8a8a67624dd.png)

## Cyclic Write

We can write back to itself or a previous vertex, but Watermark cannot retrogress, so this can only happen on a pipeline with only Map, and the data written back will implicitly be delayed.

![image3](https://user-images.githubusercontent.com/191430/235400112-ff301b71-8baa-4d10-9c78-2f9f60b5464c.png)

# Tasks

- [x] A design doc which identifies all the changes needed and challenges
- [x] Controller changes to be able to provision join vertex topologies
- [x] Watermark changes to support multi-bucket [Map/reduce]
- [x] #934
- [x] #935
- [x] #936
- [x] #946

```[tasklist]
### Tasks
```

**Comment by juliev0** [comment]
@yhl25 Per discussion today, should this be reassigned to me or no?
