### ISSUE TITLE
follow up tasks for multi-partitioned edges

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#782]
follow-up tasks of #751 

```[tasklist]
### Tasks
- [x] unit tests
- [x] e2e tests
- [x] metrics changes [link](https://github.com/numaproj/numaflow/pull/751#discussion_r1222380265)
- [x] revisit on how we pass the sink handler to metrics server [link](https://github.com/numaproj/numaflow/pull/751#discussion_r1222422726)
- [x] add partition information to buffer writer
- [x] add partitionIdx in the metric
- [ ] https://github.com/numaproj/numaflow/issues/807
```

**Comment by juliev0** [comment]
Curious - What does "add partition information to buffer writer" mean?

**Comment by yhl25** [comment]
> Curious - What does "add partition information to buffer writer" mean?

https://github.com/numaproj/numaflow/pull/802
