### ISSUE TITLE
Rethink how SDKs are exposed to Users

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#907]
The SDK interface can be confusing to users because not everything we have exposed can be manipulated, and even if the compile time check passes, the runtime may not.

Current Usability problems
- Numaflow User
  - I moved my Map function from UDF to Source (and vice-versa), and it is not working.
  - I have more than one map function; even if I register, only one takes effect.
  - I am able to register Map and Reduce but a vertex can be only Map or Reduce, not both.
  - Attaching a wrong container type to a vertex will not throw errors or warnings.
- Numaflow SDK Developer
  - Map DatumResponse has watermark and event-time details that are not used (should we then remove it?)

```[tasklist]
### Tasks
- [ ] https://github.com/numaproj/numaflow/issues/906
- [ ] https://github.com/numaproj/numaflow/issues/873
- [ ] https://github.com/numaproj/numaflow/issues/867
- [ ] https://github.com/numaproj/numaflow/issues/908
- [ ] https://github.com/numaproj/numaflow-go/issues/74
- [ ] https://github.com/numaproj/numaflow-python/issues/103
- [x] https://github.com/numaproj/numaflow-java/issues/66
- [ ] https://github.com/numaproj/numaflow-rs/issues/7
```
